// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbW-YRQT-8smnNrfTw2GvT_GNmixcEC0',
    appId: '1:737676624196:web:8dbf853da74c290c22d711',
    messagingSenderId: '737676624196',
    projectId: 'hervestagro-7cba1',
    authDomain: 'hervestagro-7cba1.firebaseapp.com',
    storageBucket: 'hervestagro-7cba1.appspot.com',
    measurementId: 'G-20ZJZ6QBX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNlvTWcBRRS9TkK1LIqUsNdL6t-roaGQ',
    appId: '1:737676624196:android:5279d4014f8c688922d711',
    messagingSenderId: '737676624196',
    projectId: 'hervestagro-7cba1',
    storageBucket: 'hervestagro-7cba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9Sxbfpvbu_LsP9Jt2AJ8HzvTqJW10Wc',
    appId: '1:737676624196:ios:cb6b29ba3c8e320d22d711',
    messagingSenderId: '737676624196',
    projectId: 'hervestagro-7cba1',
    storageBucket: 'hervestagro-7cba1.appspot.com',
    iosBundleId: 'com.example.novo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD9Sxbfpvbu_LsP9Jt2AJ8HzvTqJW10Wc',
    appId: '1:737676624196:ios:1c12f76ee76ad9af22d711',
    messagingSenderId: '737676624196',
    projectId: 'hervestagro-7cba1',
    storageBucket: 'hervestagro-7cba1.appspot.com',
    iosBundleId: 'com.example.novo.RunnerTests',
  );
}
